baseurl: /sandiego
permalink: pretty
markdown: kramdown
paginate: 5
repo: sandiego
github_org: maptime
maptime:
  chapter: MaptimeSD
  twitter: MaptimeSD
  #disqus: YOUR DISQUS USERNAME
  
future: true
gems:
  - jekyll-feed
